"""empty message

Revision ID: 207d7c1dc471
Revises: 32e678015e8e
Create Date: 2024-01-31 13:04:32.730799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207d7c1dc471'
down_revision = '32e678015e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
